######################################################################
# Automatically generated by qmake (2.01a) sam. oct. 20 12:02:01 2012
######################################################################

TEMPLATE = app
QT += webkit
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
